<?php
namespace App\Controllers;

use App\Controllers\Dashboard;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;
use CodeIgniter\Test\FeatureTestTrait;

class HomeTest extends CIUnitTestCase
{
    use FeatureTestTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $result = $this->call('get', '/');

        $result->assertSee('Dashboard', 'title');
        $result->assertOK();
    }
}
